### ISSUE TITLE
Mis-timing a recording causes looping problems

### ISSUE THREAD

**Issue by robomoto** [AudNauseum/AudNauseum#47]
I'm trying to test layering an audio track in-tempo. I'm running into an issue where, if I want to start recording at the beginning of the loop, and I hit the record button a little early.  It doesn't play for two loops, then plays during silence.

This is because the recording gets slipped to the very end of the loop, making it the master loop.  I think, we need to anchor a master loop, but that has pretty broad implications. Open to discussing.  Otherwise, I'll use a longer beat for the demo video and make sure i record and stop within a single loop iteration.

**Comment by davidmikulis** [comment]
Closed by #57 -- the first track in the list is the anchor or "master" now.
